package main

import "golang-learn/searchword"

func main() {
	//fmt.Println("======================================")
	//basic.VariableExample()
	//fmt.Println("======================================")
	//basic.FmtExample()
	//fmt.Println("======================================")
	//basic.OperatorExample()
	//fmt.Println("======================================")
	//fmt.Println(basic.Add(3, 6))
	//basic.PrintAvgScore("김일등", 80, 74, 95)
	//basic.PrintAvgScore("송이등", 88, 92, 53)
	//basic.PrintAvgScore("박삼등", 78, 73, 73)
	//c, success := basic.Divide(9, 3)
	//fmt.Println(c, success)
	//d, success := basic.Divide(9, 0)
	//fmt.Println(d, success)
	//basic.PrintNo(4)
	//fmt.Println("======================================")
	//basic.ConstExample(2)
	//fmt.Println("======================================")
	//basic.ForExample()
	//fmt.Println("======================================")
	//basic.ArrayExample()
	//fmt.Println("======================================")
	//basic.StructExample()
	//fmt.Println("======================================")
	//basic.PointerExample()
	//fmt.Println("======================================")
	//basic.StringsExample()
	//fmt.Println("======================================")
	//basic.PackageExample()
	//fmt.Println("======================================")
	////numberguess.Game()
	//fmt.Println("======================================")
	//basic.SliceExample()
	//fmt.Println("======================================")
	//basic.SlicingExample()
	//fmt.Println("======================================")
	//basic.MethodExample()
	//fmt.Println("======================================")
	//basic.InterfaceExample()
	//fmt.Println("======================================")
	//basic.Function2Example()
	//fmt.Println("======================================")
	//basic.ListExample()
	//basic.QueueExample()
	//basic.StackExample()
	//basic.MapExample()
	//fmt.Println("======================================")
	//basic.ErrorExample()
	//basic.PanicExample()
	//fmt.Println("======================================")
	//basic.GoroutineExample()
	//basic.MutexExample()
	//basic.ConcurrencyExample()
	//fmt.Println("======================================")
	//basic.ChannelExample()
	//basic.ContextExample()
	//fmt.Println("======================================")
	searchword.Run()

}
